// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-nN1wMgEK_t5HcyR70jojqJ1zqYDl6bs',
    appId: '1:840243084062:ios:66d0dcb940b0dcf6c7670f',
    messagingSenderId: '840243084062',
    projectId: 'simple-chat-ethanh',
    storageBucket: 'simple-chat-ethanh.firebasestorage.app',
    iosClientId: '840243084062-n45bab26psphdqugtib7alq72jinrqa7.apps.googleusercontent.com',
    iosBundleId: 'com.mrblankcoding.simplechat.simpleChat',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKyQwtOjNAwZfYuMXat9xbrpjdPjdqNcA',
    appId: '1:840243084062:web:2807b826a882893bc7670f',
    messagingSenderId: '840243084062',
    projectId: 'simple-chat-ethanh',
    authDomain: 'simple-chat-ethanh.firebaseapp.com',
    storageBucket: 'simple-chat-ethanh.firebasestorage.app',
  );

}